server:
  port: 9090
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rayennebr/school-management/configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/