server:
  port: 9091

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: classroom-service
          uri: lb://classroom-service
          predicates:
            - Path=/api/v1/classrooms/**
            - Path=/api/v1/grade/**
            - Path=/api/v1/classstudent/**
            - Path=/api/v1/course/**

        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/api/v1/exams/**
            - Path=/api/v1/examResults/**
            - Path=/api/v1/examTypes/**

        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/v1/students/**

        - id: teacher-service
          uri: lb://tchr
          predicates:
            - Path= /api/v1/teacher/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  healthcheck:
    enabled: true