server:
  port: 8084
spring:
  application:
    name: classroom-service
  config:
    import: optional:configserver:http://localhost:9090
  data:
    mongodb:
      uri: "mongodb://root:root@localhost:27017/class-room-service-db?authSource=admin"