server:
  port: 8081
spring:
  application:
    name: student-service
  config:
    import: optional:configserver:http://localhost:9090

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/school-management
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/school-management
resilience4j:
  circuitbreaker:
    instances:
      exam:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 50s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      exam:
        timeout-duration: 3s
  retry:
    instances:
      exam:
        max-attempts: 3
        wait-duration: 5s